### PR TITLE
Fix bug in reporting sectors

### PR DESCRIPTION
**Pull request by pstray**
A small fix to fix a python error.

### CODE REVIEW

**Comment by frbor** [comment]
I do not think this is a bug. `sectors` contains two lists, `sectors` and `unknown_sectors`:

```json
   "sectors": {    
       "sectors": [   
           "finance"    
       ],    
       "unknown_sectors": []
   }
```

See [https://github.com/mnemonic-no/act-workers/blob/master/test/scio-doc.json](https://github.com/mnemonic-no/act-workers/blob/master/test/scio-doc.json) for an example scio document.

**Comment by pstray** [comment]
That may be what it should have been, but it was definitely just a list.... without that patch, it dies with the following error-message:

`AttributeError: 'list' object has no attribute 'get'`

**Comment by frbor** [comment]
I'm sorry for the confusion, but I do think this errors occurs when the old act-scio, which is documented in the act documentation repos, is used (instead of act-scio2 which is a reimplemntation of scio).

We will update the doc to point to act-scio2.

**Comment by pstray** [comment]
That seems like a likely cause.  Maybe the doc format should have a version field so this kind of bugs could be handled more gracefully ;)

**Pull request closed without merging**
